name: Post on Social Media at 9 AM
permissions:
  pull-requests: read
  contents: read
on:
  #  schedule:
  #    - cron: '30 3 * * *' # codespell:ignore; Runs at 3:30 AM UTC every day (9:00 AM IST)
  #      Temporarily disabled; re-enable when automated posting is required.
  workflow_dispatch: # Optional, allows manual trigger from GitHub UI
jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    environment: SocialMediaPost
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v5
      # Install uv tool
      - name: Install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3
      # Run the application
      - name: Run App
        env:
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          MODEL_API_KEY: ${{ secrets.MODEL_API_KEY }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: |
          make run
